/**
 * Env-driven limits for the drop server's abuse/overload guards.
 *
 * Every value has a safe, finite default so the guards are active even when
 * nothing is set — there is deliberately no "unlimited" fallback. Operators
 * tune these via systemd `Environment=` lines; see drop-server/README.md.
 *
 * Mirrors collab-server/src/config.ts.
 */

function num(name: string, fallback: number): number {
  const raw = process.env[name];
  if (raw === undefined || raw.trim() === "") return fallback;
  const n = Number(raw);
  if (!Number.isFinite(n) || n < 0) {
    console.warn(`[config] ${name}="${raw}" is not a non-negative number; using default ${fallback}`);
    return fallback;
  }
  return n;
}

const MB = 1024 * 1024;

export const limits = {
  /** P0 — maximum accepted upload size (ciphertext bytes). */
  maxDropBytes: num("MAX_DROP_BYTES", 200 * MB),

  /**
   * P1 — minimum plausible ciphertext. A sealed box is 48 bytes of overhead
   * (32-byte ephemeral public key + 16-byte MAC), so anything shorter cannot
   * be one and is rejected before touching disk.
   */
  minDropBytes: 48,
  /** P1 — client-declared filename length cap (characters, post-decode). */
  maxFilenameLen: num("MAX_FILENAME_LEN", 200),

  /** P2 — per-IP sliding-window drop-count guard. */
  rateWindowMs: num("RATE_WINDOW_MS", 60_000),
  rateMaxDropsPerWindow: num("RATE_MAX_DROPS_PER_WINDOW", 10),

  /** P3 — warn about drops older than this (admin pickup reminder). */
  dropMaxAgeWarnDays: num("DROP_MAX_AGE_WARN_DAYS", 30),
  /** P3 — hard-delete drops older than this. 0 (the default) = never. */
  dropTtlDays: num("DROP_TTL_DAYS", 0),
  /** P3 — sweep cadence. */
  sweepIntervalMs: num("SWEEP_INTERVAL_MS", 24 * 60 * 60 * 1000),

  /** P4 — warn when total stored bytes pass this. */
  storageWarnBytes: num("STORAGE_WARN_BYTES", 1024 * MB),
  /** P4 — refuse uploads (HTTP 507) when total stored bytes pass this. */
  storageMaxBytes: num("STORAGE_MAX_BYTES", 2048 * MB),
} as const;

export type Limits = typeof limits;

/**
 * The X25519 public key uploads are sealed to, base64 (44 chars for 32 bytes).
 * Generated by tools/drop_keygen.py on the ADMIN machine — the matching
 * private key must never reach this server. Required: without it the service
 * cannot describe what to encrypt to, so it refuses to start.
 */
export function publicKey(): string {
  const raw = (process.env.DROP_PUBLIC_KEY ?? "").trim();
  const bytes = raw ? Buffer.from(raw, "base64") : Buffer.alloc(0);
  // Round-trip check: catches truncated/garbage base64, not just emptiness.
  if (bytes.length !== 32 || bytes.toString("base64") !== raw) {
    throw new Error(
      "DROP_PUBLIC_KEY must be the base64 X25519 public key printed by tools/drop_keygen.py",
    );
  }
  return raw;
}

export const dataDir = process.env.DATA_DIR ?? "./data/drops";
export const host = process.env.HOST ?? "127.0.0.1";
export const port = num("PORT", 5175);
