#!/usr/bin/env bash
#
# setup_drop_server.sh — provision one secure-drop (E2E-encrypted upload) instance.
#
# Builds the drop server from the map repo's drop-server/ package and runs it
# as a hardened systemd service on 127.0.0.1:<port>, behind its OWN nginx site
# (default: aanleveren.woonzorglimburg.nl) serving the standalone upload page
# at / and proxying POST /drop to the service.
#
# The service stores ONLY ciphertext: browsers seal files to the public key
# given via --pubkey (generated by drop-server/tools/drop_keygen.py on the
# ADMIN machine — the private key must never reach this server). Retrieval is
# out-of-band: scp the data dir, decrypt locally with tools/drop_decrypt.py.
# Read drop-server/README.md (incl. the AVG section) before exposing.
#
# Prerequisites (manual, before running):
#   * DNS A record for the hostname pointing at this server. Add an AAAA only
#     if the host's IPv6 is pinned — see server/README.md on SLAAC rotation.
#   * The keypair: uv run drop-server/tools/drop_keygen.py
#
# Run ON the target server. Auto-deploys on push via the shared webhook daemon:
# https://<host>/hooks/deploy-<slug>.
#
# Example:
#   ./setup_drop_server.sh -y \
#       --slug woonzorglimburg_drop --port 5175 \
#       --host aanleveren.woonzorglimburg.nl \
#       --pubkey 'BASE64PUBKEY=' \
#       --repo git@github.com:ObjectVision/northwake.git \
#       --email eoudejans@objectvision.nl

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

usage() {
  cat <<EOF
${_C_BOLD}setup_drop_server.sh${_C_RESET} — provision a secure-drop (E2E-encrypted upload) server.

Usage: $0 [options]

Options:
$(print_kv "--slug NAME"      "instance id, namespaces all paths (e.g. woonzorglimburg_drop)")
$(print_kv "--host FQDN"      "public hostname (default: aanleveren.woonzorglimburg.nl)")
$(print_kv "--port N"         "localhost port the service listens on (default: 5175)")
$(print_kv "--pubkey B64"     "X25519 public key from tools/drop_keygen.py (required)")
$(print_kv "--repo URL"       "git remote of the map repo (contains drop-server/)")
$(print_kv "--branch NAME"    "git branch to deploy (default: main)")
$(print_kv "--node-version N" "Node.js major version to install if missing (default: 20)")
$(print_kv "--email ADDR"     "certbot registration/expiry email")
$(print_kv "--secret HEX"     "GitHub webhook HMAC secret (default: generated)")
$(print_kv "--no-tls"         "skip certbot (plain HTTP; testing only)")
$(print_kv "-y, --yes"        "non-interactive: accept all defaults")
$(print_kv "-h, --help"       "show this help")
EOF
}

SLUG=""; HOST_FQDN=""; PORT=""; PUBKEY=""; REPO=""; BRANCH=""
NODE_VERSION=""; EMAIL=""; SECRET=""; NO_TLS=0

while [ $# -gt 0 ]; do
  case "$1" in
    --slug)           SLUG="$2"; shift 2 ;;
    --slug=*)         SLUG="${1#*=}"; shift ;;
    --host)           HOST_FQDN="$2"; shift 2 ;;
    --host=*)         HOST_FQDN="${1#*=}"; shift ;;
    --port)           PORT="$2"; shift 2 ;;
    --port=*)         PORT="${1#*=}"; shift ;;
    --pubkey)         PUBKEY="$2"; shift 2 ;;
    --pubkey=*)       PUBKEY="${1#*=}"; shift ;;
    --repo)           REPO="$2"; shift 2 ;;
    --repo=*)         REPO="${1#*=}"; shift ;;
    --branch)         BRANCH="$2"; shift 2 ;;
    --branch=*)       BRANCH="${1#*=}"; shift ;;
    --node-version)   NODE_VERSION="$2"; shift 2 ;;
    --node-version=*) NODE_VERSION="${1#*=}"; shift ;;
    --email)          EMAIL="$2"; shift 2 ;;
    --email=*)        EMAIL="${1#*=}"; shift ;;
    --secret)         SECRET="$2"; shift 2 ;;
    --secret=*)       SECRET="${1#*=}"; shift ;;
    --no-tls)         NO_TLS=1; shift ;;
    -y|--yes)         ASSUME_YES=1; shift ;;
    -h|--help)        usage; exit 0 ;;
    *) die "Unknown option: $1 (see --help)" ;;
  esac
done

log "Secure-drop server setup"
require_sudo

ask SLUG "Instance slug" ""
validate_slug "$SLUG"
ask HOST_FQDN    "Public hostname"                    "aanleveren.woonzorglimburg.nl"
validate_host "$HOST_FQDN"
ask PORT         "Listen port (127.0.0.1)"            "5175"
[[ "$PORT" =~ ^[0-9]+$ ]] || die "Invalid port '$PORT'."
ask PUBKEY       "Drop public key (base64, from drop_keygen.py)" ""
# 32 bytes -> 44 base64 chars ending in '='. Reject early: a wrong key here
# means every upload is sealed to something the admin cannot open.
[[ "$PUBKEY" =~ ^[A-Za-z0-9+/]{43}=$ ]] || die "Invalid --pubkey (expect 44 base64 chars for 32 bytes)."
ask REPO         "Git repository URL (map repo)"      ""
ask BRANCH       "Git branch"                         "main"
ask NODE_VERSION "Node.js major version"              "20"
[ "$NO_TLS" = "1" ] || ask EMAIL "Certbot email" ""
ask_secret SECRET "GitHub webhook secret (HMAC)"

REPO_DIR="/srv/$SLUG"
DATA_DIR="/var/lib/$SLUG"
PAGE_DIR="$REPO_DIR/drop-server/page"
SERVICE_NAME="drop-$SLUG"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
DEPLOY_SCRIPT="/usr/local/bin/deploy-$SLUG.sh"
DEPLOY_LOG="/var/log/$SLUG-deploy.log"
TOGGLE_SCRIPT="/usr/local/bin/drop-toggle-$SLUG"
HOOK_ID="deploy-$SLUG"

echo
log "Plan"
info "slug            : $SLUG"
info "hostname        : $HOST_FQDN (own nginx site + cert)"
info "repo / branch   : $REPO ($BRANCH)"
info "repo dir        : $REPO_DIR"
info "listen          : 127.0.0.1:$PORT"
info "data (blobs)    : $DATA_DIR/drops/  (ciphertext only)"
info "upload page     : $PAGE_DIR -> https://$HOST_FQDN/"
info "systemd service : $SERVICE_NAME"
info "webhook hook id : $HOOK_ID  ->  https://$HOST_FQDN/hooks/$HOOK_ID"
echo
confirm "Proceed?" || die "Aborted."

# --- 1. base packages ---
ensure_base_stack
# No build-essential: drop-server has zero native deps (deliberately).

# --- 2. Node.js ---
install_node() {
  if command -v node >/dev/null 2>&1; then
    ok "Node.js already installed: $(node -v)"
    return
  fi
  log "Installing Node.js ${NODE_VERSION} LTS"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_VERSION}.x" | sudo -E bash -
  ensure_packages nodejs
  ok "Installed Node.js $(node -v), npm $(npm -v)"
}
install_node

# --- 3. directories ---
log "Creating directories"
sudo mkdir -p "$DATA_DIR"
sudo chown "$DEPLOY_USER:$DEPLOY_USER" "$DATA_DIR"
sudo chmod 750 "$DATA_DIR"
ok "Data directory ready ($DATA_DIR; drops/ is created by the service, 0700 via UMask)"

# --- 4. clone repo + first build (incl. vendoring libsodium for the page) ---
ensure_repo "$REPO" "$BRANCH" "$REPO_DIR"
log "First build (npm ci && tsc && page:vendor in drop-server/)"
(
  cd "$REPO_DIR/drop-server"
  npm ci
  npx --no-install tsc
  npm run page:vendor
)
ok "Built drop server + upload page assets"

# --- 5. systemd service (hardened beyond the collab unit: this one faces the
#        open internet and holds — albeit encrypted — personal data) ---
log "Writing systemd unit $SERVICE_FILE"
write_root_file "$SERVICE_FILE" 0644 <<EOF
[Unit]
Description=Secure-drop (E2E-encrypted upload) server — $SLUG
After=network.target

[Service]
Type=simple
User=${DEPLOY_USER}
Group=${DEPLOY_USER}
WorkingDirectory=${REPO_DIR}/drop-server
Environment=PORT=${PORT}
Environment=DATA_DIR=${DATA_DIR}/drops
# The X25519 public key uploads are sealed to. The matching PRIVATE key lives
# only on the admin machine (tools/drop_keygen.py). Rotate by editing this
# line + daemon-reload + restart — note rotation protects FUTURE drops only.
Environment=DROP_PUBLIC_KEY=${PUBKEY}
# Overload / storage guards — all optional; safe finite defaults apply if
# unset. See drop-server/README.md "Abuse & overload guards".
#Environment=MAX_DROP_BYTES=209715200
#Environment=RATE_MAX_DROPS_PER_WINDOW=10
#Environment=DROP_MAX_AGE_WARN_DAYS=30
#Environment=DROP_TTL_DAYS=0
#Environment=STORAGE_MAX_BYTES=2147483648
ExecStart=$(command -v node) ${REPO_DIR}/drop-server/dist/index.js
Restart=always
RestartSec=5s

# Sandbox: the process can write ONLY its data dir; everything else read-only.
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=${DATA_DIR}
ProtectHome=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictAddressFamilies=AF_INET AF_INET6
CapabilityBoundingSet=
# @system-service alone SIGSYS-kills Node at startup: V8 (Node >= 20) uses
# memory protection keys (pkey_alloc, syscall 330) which the group omits.
SystemCallFilter=@system-service pkey_alloc pkey_free pkey_mprotect
UMask=0077

[Install]
WantedBy=multi-user.target
EOF
sudo systemctl daemon-reload
sudo systemctl enable --now "$SERVICE_NAME"
ok "Service $SERVICE_NAME enabled and started"

# --- 6. deploy script + webhook (same shape as the collab server) ---
log "Writing deploy script $DEPLOY_SCRIPT"
write_root_file "$DEPLOY_SCRIPT" 0755 <<EOF
#!/usr/bin/env bash
# Detach the actual work so the webhook responds within GitHub's 10s timeout.
setsid -f bash -c '
set -euo pipefail
exec >> $DEPLOY_LOG 2>&1
echo "--- Deploy started: \$(date --iso-8601=seconds) ---"

cd $REPO_DIR
git fetch --prune origin
git reset --hard origin/$BRANCH

cd drop-server
npm ci
npx --no-install tsc
npm run page:vendor

sudo systemctl restart $SERVICE_NAME

echo "--- Deploy finished: \$(date --iso-8601=seconds) ---"
' < /dev/null > /dev/null 2>&1
echo "Deploy started in background (see $DEPLOY_LOG)"
EOF
sudo touch "$DEPLOY_LOG"
sudo chown "$DEPLOY_USER:$DEPLOY_USER" "$DEPLOY_LOG"
write_root_file "/etc/sudoers.d/$SERVICE_NAME" 0440 <<EOF
${DEPLOY_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart ${SERVICE_NAME}
EOF
ok "Deploy script and log ready"

# --- 6b. open/close switch ---
# Flips a state file the service reads per request; the unit keeps running (and
# keeps answering healthz) while closed, so no sudo and no systemctl involved —
# the invoking user already owns $DATA_DIR. State survives deploys and reboots
# because it lives in $DATA_DIR, which the deploy's `git reset --hard` never
# touches.
log "Writing open/close switch $TOGGLE_SCRIPT"
write_root_file "$TOGGLE_SCRIPT" 0755 <<EOF
#!/usr/bin/env bash
# Open or close the secure drop for $SLUG. Usage: $(basename "$TOGGLE_SCRIPT") <status|open|close> [--reason "<text>"]
exec env DATA_DIR=${DATA_DIR}/drops $(command -v node) ${REPO_DIR}/drop-server/dist/cli.js "\$@"
EOF
ok "Open/close switch ready ($TOGGLE_SCRIPT)"

ensure_webhook_daemon
webhook_upsert_hook "$HOOK_ID" "$DEPLOY_SCRIPT" "$REPO_DIR" "$SECRET" "$BRANCH"

# --- 7. nginx: rate-limit zone + site ---
log "Writing nginx rate-limit zone"
# http-context snippet; conf.d files are included inside http{} by default.
write_root_file /etc/nginx/conf.d/drop-ratelimit.conf 0644 <<EOF
# Secure-drop upload flood guard (outer wall; the service also rate-limits
# in-process). 6 uploads/minute per client IP, small burst.
limit_req_zone \$binary_remote_addr zone=drop:1m rate=6r/m;
EOF

log "Writing nginx site"
# CSP: the page is fully self-contained (vendored libsodium, no CDN, no
# external calls beyond its own origin), so the policy can be strict AND
# enforcing from day one — unlike the map app there is nothing to break.
CSP_DROP="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; \
img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; \
form-action 'self'"

nginx_write_site "$SLUG" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $HOST_FQDN;

    root $PAGE_DIR;
    index index.html;

$(render_csp_header "$CSP_DROP" 0 "'none'")

    # The upload endpoint: proxied to the loopback service. IPs are kept out
    # of the access log (AVG data minimization) — errors still log.
    location /drop {
        proxy_pass http://127.0.0.1:$PORT;
        client_max_body_size 201m;
        limit_req zone=drop burst=5 nodelay;
        proxy_request_buffering on;
        access_log off;
    }

    # Proxy deploy webhooks to the shared listener (same block as the map app).
    location /hooks/ {
        proxy_pass http://127.0.0.1:$WEBHOOK_PORT/hooks/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 30s;
    }

    # Static upload page. Uploads are anonymous; there is nothing to cache-bust
    # aggressively, but don't let stale HTML pin an old vendor bundle.
    location / {
        try_files \$uri \$uri/ =404;
        add_header Cache-Control "no-cache" always;
    }

    location = /.well-known/security.txt { default_type text/plain; }
}
EOF
nginx_enable_site "$SLUG"
nginx_test_reload

# --- 8. TLS ---
if [ "$NO_TLS" = "1" ]; then
  warn "TLS skipped (--no-tls). NEVER expose this without TLS in production."
else
  ensure_hsts_snippet
  ensure_tls_hardening_snippet
  tls_obtain "$EMAIL" "$HOST_FQDN" || true
  nginx_post_tls "$SLUG" "$HOST_FQDN"
  ensure_security_txt "$PAGE_DIR" "https://$HOST_FQDN"
  check_aaaa "$HOST_FQDN"
  nginx_test_reload
fi

SCHEME=$([ "$NO_TLS" = 1 ] && echo http || echo https)
echo
ok "Secure-drop server '$SLUG' is set up."
info "Upload page  : $SCHEME://$HOST_FQDN/"
info "Endpoint     : $SCHEME://$HOST_FQDN/drop   (pubkey: $SCHEME://$HOST_FQDN/drop/pubkey)"
info "Data dir     : $DATA_DIR/drops  (retrieve: scp -r $DEPLOY_USER@$HOST_FQDN:$DATA_DIR/drops .)"
info "Decrypt with : uv run drop-server/tools/drop_decrypt.py --key drop-secret.key ./drops"
info "Open/close   : $(basename "$TOGGLE_SCRIPT") <status|open|close> [--reason \"<text>\"]  (over ssh, no sudo)"
echo
log "Configure the GitHub webhook on the source repo:"
info "Payload URL  : https://$HOST_FQDN/hooks/$HOOK_ID"
info "Content type : application/json"
info "Secret       : $SECRET"
info "Events       : Just the push event"
echo
warn "The private key (drop-secret.key) is the ONLY way to read drops."
warn "Back it up now; losing it makes all received data permanently unreadable."
